import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Shapes} from "@/components/Shapes";
import Header from "@/components/header";
import Intro from "@/components/intro";
import SectionDivider from "@/components/section-divider";
import About from "@/components/about";
import Link from "next/link";
import React from "react";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className="!scroll-smooth">
      <body className={`${inter.className} bg-neutral-50 text-black w-screen`}>
      <div
          className="bg-gradient-to-br from-cyan-200 to-pink-200 absolute h-screen w-screen -z-10 rounded-full blur-[100rem] sm:w-screen">
      </div>

      <Header/>
      {children}
      {/*<Footer/>*/}


      {/*<div className="h-screen w-screen"*/}
      {/*     >*/}
      {/*<Header/>*/}

      {/*<SectionDivider/>*/}

      {/*<SectionDivider/>*/}

      </body>
      </html>
  );
}
