import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Shapes} from "@/components/Shapes";
import Header from "@/components/header";
import Intro from "@/components/intro";
import SectionDivider from "@/components/section-divider";
import About from "@/components/about";
import Link from "next/link";
import React from "react";
import ActiveSectionContextProvider from "@/context/active-section-context";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Parth Patel",
  description: "Generated by Parth Patel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className="!scroll-smooth">
      <body className={`${inter.className} bg-neutral-50 text-black`}>


      <ActiveSectionContextProvider>
          <Header/>
          {children}
      </ActiveSectionContextProvider>



      </body>
      </html>
  );
}
