import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import React from "react";
import ActiveSectionContextProvider from "@/context/active-section-context";
import { Analytics } from '@vercel/analytics/react';
import Footer from "@/components/footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Parth Patel",
  description: "Generated by Parth Patel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className="!scroll-smooth">
      <body className={`${inter.className} bg-neutral-50 text-black`}>


      <ActiveSectionContextProvider>
          <Header/>
          {children}
          <Footer/>
      </ActiveSectionContextProvider>


      <Analytics/>
      </body>
      </html>
  );
}
